services:
  victim:
    build:
      context: ./apache-config
      dockerfile: Dockerfile
    container_name: victim
    volumes:
      - ./apache-config/httpd-2.4.63.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache-config/htdocs:/usr/local/apache2/htdocs
      - ./dataset/access.log:/var/log/apache2/access.log
    ports:
      - "8080:80"
    restart: always

