{
 "title": "Apache Victim Server Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,2m,3m,5m,7m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(container_cpu_user_seconds_total{job=~\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Apache UP/DOWN",
   "type": "status-history",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "apache_up{instance=~\"apache-exporter:9117\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache Worker Statuses",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_workers{instance=\"apache-exporter:9117\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Apache CPU load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(container_cpu_usage_seconds_total{name=\"victim\"}[$interval])) by (name) /\nsum(container_spec_cpu_quota{name=\"victim\"}/container_spec_cpu_period{name=\"victim\"}) by (name))* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"victim\"} and container_last_seen{name=\"victim\"} > (time() - 20)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=\"victim\"}[$interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=\"victim\"}[$interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}